if(NOT TARGET zlib)
  if(CMAKE_MAKE_PROGRAM MATCHES "(MSBuild|devenv|msdev|nmake)")
    set(CMAKE_OLD_C_FLAGS ${CMAKE_C_FLAGS})
    set(CMAKE_OLD_CXX_FLAGS ${CMAKE_CXX_FLAGS})
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /wd4127 /wd4131 /wd4244")
    set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} /wd4127 /wd4131 /wd4244")
  endif()
  option(AMD64 "Enable building amd64 assembly implementation" ON)
  add_subdirectory("zlib")
  set_target_properties(zlib zlibstatic example minigzip PROPERTIES FOLDER modules/zlib)
  set_target_properties(example minigzip PROPERTIES EXCLUDE_FROM_ALL 1 EXCLUDE_FROM_DEFAULT_BUILD 1)
  if(CMAKE_MAKE_PROGRAM MATCHES "(MSBuild|devenv|msdev|nmake)")
    set(CMAKE_C_FLAGS ${CMAKE_OLD_C_FLAGS})
    set(CMAKE_CXX_FLAGS ${CMAKE_OLD_CXX_FLAGS})
  endif()
endif()
