var searchData=
[
  ['raw',['raw',['../class_cpp_logging_1_1_record.html#a53fb6876e9bcb49289e0447ed79d6415',1,'CppLogging::Record']]],
  ['record',['Record',['../class_cpp_logging_1_1_record.html',1,'CppLogging::Record'],['../class_cpp_logging_1_1_record.html#a9869b96b578bbb85709cdaec079526ee',1,'CppLogging::Record::Record()'],['../class_cpp_logging_1_1_record.html#aa27f6c8c7b1593d38ad4c28294df63c9',1,'CppLogging::Record::Record(const Record &amp;)=default'],['../class_cpp_logging_1_1_record.html#aafb916fa6c565ff7735e18d4e52e6f81',1,'CppLogging::Record::Record(Record &amp;&amp;)=default']]],
  ['record_2eh',['record.h',['../record_8h.html',1,'']]],
  ['record_2einl',['record.inl',['../record_8inl.html',1,'']]],
  ['rolling_5ffile_5fappender_2ecpp',['rolling_file_appender.cpp',['../rolling__file__appender_8cpp.html',1,'']]],
  ['rolling_5ffile_5fappender_2eh',['rolling_file_appender.h',['../rolling__file__appender_8h.html',1,'']]],
  ['rollingfileappender',['RollingFileAppender',['../class_cpp_logging_1_1_rolling_file_appender.html',1,'CppLogging::RollingFileAppender'],['../class_cpp_logging_1_1_rolling_file_appender.html#a8227d016c9848a0b5c224df131063d64',1,'CppLogging::RollingFileAppender::RollingFileAppender(const CppCommon::Path &amp;path, TimeRollingPolicy policy=TimeRollingPolicy::DAY, const std::string &amp;pattern=&quot;{UtcDateTime}.log&quot;, bool archive=false, bool truncate=false, bool auto_flush=false)'],['../class_cpp_logging_1_1_rolling_file_appender.html#aec5894fa4d8f2f9e11ade7e3285e5eef',1,'CppLogging::RollingFileAppender::RollingFileAppender(const CppCommon::Path &amp;path, const std::string &amp;filename, const std::string &amp;extension, size_t size=104857600, size_t backups=10, bool archive=false, bool truncate=false, bool auto_flush=false)'],['../class_cpp_logging_1_1_rolling_file_appender.html#abcf828106ffc0f8df6fbd4b447d23c8b',1,'CppLogging::RollingFileAppender::RollingFileAppender(const RollingFileAppender &amp;)=delete'],['../class_cpp_logging_1_1_rolling_file_appender.html#a6eeba6d9f179a8fb2605030591db7fea',1,'CppLogging::RollingFileAppender::RollingFileAppender(RollingFileAppender &amp;&amp;appender) noexcept']]]
];
