name: Windows (Visual Studio)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Visual Studio"
        uses: egor-tensin/vs-shell@v2

      - name: "Setup cmake"
        run: cmake --version

      - name: "Setup gil"
        run: |
          pip3 install gil
          gil update

      - name: "Build"
        run: |
          cd build
          ./vs.bat
